title: Tanishq Jain - Technical Portfolio
description: Robotics, AI, and Engineering Projects
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false

author:
  name: Tanishq Jain
  email: tjai8597@gmail.com
  github: Tanishq8597
